server:
  port: 8080

spring:
  datasource:
    type:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.54.50.28:3306/5620?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

openai:
  token: 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

